const routes = require('next-routes')

module.exports = routes()
  .add('index')
  .add('flights')
  .add('searchDemo', '/searchDemo', 'search')
  .add('flight', '/flight/:origin/:destination')
  .add('search', '/search','routes')
  .add('origin', '/search/:origin', 'origin')
  .add('route', '/search/:origin/:destination', 'route')
